// itab-gen-client reads `/api/meta/collections` and emits a
// self-contained TypeScript client (interfaces + per-collection CRUD object).
//
// Usage:
//
//	go run github.com/iForcecome/itabbase/server/cmd/itab-gen-client \
//	    --url http://localhost:8080/itab/foo/api/meta/collections \
//	    --base-url /itab/foo/api \
//	    --out client/src/api/kernel.ts
//
// If the meta endpoint requires auth, set the COOKIE env var to a copy of the
// browser session (e.g. COOKIE='itab-sid=...').
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

type field struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	Required bool   `json:"required"`
	MaxLen   int    `json:"max_len"`
	Target   string `json:"target,omitempty"`
	Through  string `json:"through,omitempty"`
}

type collection struct {
	Name    string  `json:"name"`
	Display string  `json:"display"`
	Fields  []field `json:"fields"`
}

type metaResp struct {
	Data []collection `json:"data"`
}

func main() {
	var url, baseURL, out string
	flag.StringVar(&url, "url", "", "URL of the meta endpoint, e.g. http://host/<prefix>/api/meta/collections")
	flag.StringVar(&baseURL, "base-url", "/api", "kernel API base URL baked into the generated client")
	flag.StringVar(&out, "out", "kernel-client.ts", "output file path")
	flag.Parse()
	if url == "" {
		fmt.Fprintln(os.Stderr, "itab-gen-client: --url is required")
		flag.Usage()
		os.Exit(1)
	}

	cols, err := fetchMeta(url)
	if err != nil {
		fail("fetch meta: %v", err)
	}
	if len(cols) == 0 {
		fail("meta endpoint returned no collections")
	}

	src := generate(cols, baseURL)
	if err := os.WriteFile(out, []byte(src), 0o644); err != nil {
		fail("write %s: %v", out, err)
	}
	fmt.Printf("itab-gen-client: wrote %d collections to %s\n", len(cols), out)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "itab-gen-client: "+format+"\n", args...)
	os.Exit(1)
}

func fetchMeta(url string) ([]collection, error) {
	req, err := http.NewRequest("GET", url, nil)
	if err != nil {
		return nil, err
	}
	if c := strings.TrimSpace(os.Getenv("COOKIE")); c != "" {
		req.Header.Set("Cookie", c)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	var m metaResp
	if err := json.NewDecoder(resp.Body).Decode(&m); err != nil {
		return nil, err
	}
	cols := m.Data
	sort.Slice(cols, func(i, j int) bool { return cols[i].Name < cols[j].Name })
	return cols, nil
}

func generate(cols []collection, baseURL string) string {
	var b strings.Builder
	b.WriteString(header(baseURL))
	for _, c := range cols {
		b.WriteString("\n// === " + c.Name + " ===\n")
		b.WriteString(genInterface(c))
		b.WriteString(genClient(c))
	}
	return b.String()
}

func header(baseURL string) string {
	return fmt.Sprintf(`// Generated by itab-gen-client; DO NOT EDIT.
// Regenerate after schema changes.

export type ID = string | number

export interface ListQuery {
  page?: number
  size?: number
  sort?: string
  include?: string
  filter?: Record<string, string | number | boolean>
}

export interface ListResult<T> {
  data: T[]
  total: number
  page: number
  size: number
}

let baseURL = %q
export function setBaseURL(url: string): void {
  baseURL = url
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  const init: RequestInit = { method, credentials: 'include' }
  if (body !== undefined) {
    init.headers = { 'Content-Type': 'application/json' }
    init.body = JSON.stringify(body)
  }
  const res = await fetch(baseURL + path, init)
  if (!res.ok) {
    let msg = method + ' ' + path + ' ' + res.status
    try {
      const e = (await res.json()) as { error?: string }
      if (e?.error) msg += ': ' + e.error
    } catch {
      // ignore
    }
    throw new Error(msg)
  }
  return (await res.json()) as T
}

function qs(p?: ListQuery): string {
  if (!p) return ''
  const params = new URLSearchParams()
  if (p.page) params.set('page', String(p.page))
  if (p.size) params.set('size', String(p.size))
  if (p.sort) params.set('sort', p.sort)
  if (p.include) params.set('include', p.include)
  if (p.filter)
    for (const [k, v] of Object.entries(p.filter)) params.set('filter[' + k + ']', String(v))
  const s = params.toString()
  return s ? '?' + s : ''
}
`, baseURL)
}

func genInterface(c collection) string {
	var b strings.Builder
	b.WriteString("export interface " + typeName(c.Name) + " {\n")
	b.WriteString("  id: number\n")
	for _, f := range c.Fields {
		if f.Type == "has_many" {
			continue
		}
		opt := "?"
		if f.Required {
			opt = ""
		}
		b.WriteString("  " + f.Name + opt + ": " + tsType(f) + "\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func tsType(f field) string {
	switch f.Type {
	case "string", "text", "datetime":
		return "string"
	case "int", "float", "belongs_to":
		return "number"
	case "bool":
		return "boolean"
	}
	return "unknown"
}

func genClient(c collection) string {
	t := typeName(c.Name)
	p := "/" + c.Name
	return fmt.Sprintf(`
export const %s = {
  list: (q?: ListQuery) => request<ListResult<%s>>('GET', %q + qs(q)),
  get: (id: ID) => request<{ data: %s }>('GET', %q + '/' + id),
  create: (data: Partial<%s>) => request<{ data: %s }>('POST', %q, data),
  update: (id: ID, data: Partial<%s>) =>
    request<{ data: %s }>('PATCH', %q + '/' + id, data),
  delete: (id: ID) => request<{ data: { id: ID } }>('DELETE', %q + '/' + id),
}
`, c.Name, t, p, t, p, t, t, p, t, t, p, p)
}

// typeName turns a snake_case plural collection name into a PascalCase singular
// type name. Naive: PascalCase + drop trailing "s". Edge cases (categories,
// news, ...) need manual override; documented as a v1.0 limitation.
func typeName(s string) string {
	if s == "" {
		return s
	}
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	out := b.String()
	if strings.HasSuffix(out, "s") {
		out = strings.TrimSuffix(out, "s")
	}
	return out
}
